### ISSUE TITLE
Edit the homepage styling... Version 2

### ISSUE THREAD

**Issue by Jason897571** [Jason897571/Meal-Map#20]
For this issue I will fix the existing search bar by implementing one of my own.

this will allow us to only utilize one component for search engine as well as run tereney operator based if the use has searched any places. if not, then ask the user to search for something to begin!

EXAMPLE: 

{
searchedPlaces.length ? true : false
}

**Comment by Sajjadalgburi** [comment]
![Image](https://github.com/Jason897571/Meal-Map/assets/137656932/c6a9a534-88c2-4977-8810-73f0ba5ab0a5)

**Comment by Sajjadalgburi** [comment]
currently have switched the file structure and made it so that the served hompage displays the searched results after the user inputs it in the filed.

this is just a demo:


![Image](https://github.com/Jason897571/Meal-Map/assets/137656932/4733cb50-4c79-4571-aae4-47ae6405e5b2)

**Comment by Sajjadalgburi** [comment]
i have finished the styling for main page. I will then need @garrethil 's help to implement the logic for displaying the searched locations !



![Image](https://github.com/Jason897571/Meal-Map/assets/137656932/9e15f626-158f-4a8c-8961-7e16ec434487)
